# Generated by Django 3.2 on 2023-02-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230204_1029'),
    ]

    operations = [
    ]
