# Generated by Django 3.2 on 2023-02-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230203_2010'),
        ('reviews', '0005_merge_0002_auto_20230204_1029_0004_auto_20230203_2010'),
    ]

    operations = [
    ]
