# Generated by Django 3.2 on 2023-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230202_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(to='reviews.Genre'),
        ),
    ]
